const $=s=>document.querySelector(s), STORE='phoen-smartcard', HISTORY='phoen-smartcard-history', FAV='phoen-smartcard-favorites';let active=null, shared=false, promptEvent=null;
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}, write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('hidden','#'+x.id!==id));scrollTo(0,0)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function encode(d){return btoa(unescape(encodeURIComponent(JSON.stringify(d)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function decode(v){try{v=v.replace(/-/g,'+').replace(/_/g,'/');while(v.length%4)v+='=';return JSON.parse(decodeURIComponent(escape(atob(v))))}catch{return null}}
function url(v){return v&&!/^https?:\/\//i.test(v)?'https://'+v:v||''}
function key(d){return [d.name,d.email,d.phone].join('|').toLowerCase()}
function shareUrl(d){const x=new URL(location.href);x.search='';x.hash='';x.searchParams.set('shared',encode(d));return x.toString()}
function vcard(d){return `BEGIN:VCARD\r\nVERSION:3.0\r\nFN:${d.name||''}\r\nORG:${d.company||''}\r\nTITLE:${d.role||''}\r\nEMAIL:${d.email||''}\r\nTEL:${d.phone||''}\r\nURL:${url(d.website)}\r\nEND:VCARD`}
function drawQR(el,text,size=420){el.innerHTML='';try{const q=new QRCode(0,'M');q.addData(text);q.make();const count=q.getModuleCount(),c=document.createElement('canvas'),ctx=c.getContext('2d'),cell=Math.floor(size/count),real=cell*count;c.width=c.height=real;ctx.fillStyle='#fff';ctx.fillRect(0,0,real,real);ctx.fillStyle='#000';for(let r=0;r<count;r++)for(let col=0;col<count;col++)if(q.isDark(r,col))ctx.fillRect(col*cell,r*cell,cell,cell);el.append(c)}catch{el.textContent='QR library unavailable';}}
function isFav(d){return read(FAV).includes(key(d))}
function favorite(d){let f=read(FAV),k=key(d);f=f.includes(k)?f.filter(x=>x!==k):[...f,k];write(FAV,f);updateFav();renderHistory()}
function updateFav(){if(!active)return;$('#favoriteBtn').textContent=isFav(active)?'★':'☆';$('#favoriteBtn').classList.toggle('active',isFav(active))}
function saveHistory(d){let h=read(HISTORY).filter(x=>key(x)!==key(d));h.unshift({...d,time:Date.now()});write(HISTORY,h.slice(0,30))}
function render(d,isShared=false,record=true){active=d;shared=isShared;$('#nameText').textContent=d.name||'Unnamed contact';$('#roleText').textContent=d.role||'';$('#companyText').textContent=d.company||'SMARTCARD';$('#qrName').textContent=d.name||'Connect';const fields=[['email',d.email,'mailto:'+d.email],['phone',d.phone,'tel:'+d.phone],['web',d.website,url(d.website)]];fields.forEach(([n,v,href])=>{const a=$('#'+n+'Action');a.classList.toggle('hidden',!v);a.href=v?href:'#';$('#'+n+'Text').textContent=v||''});const im=$('#photo');im.classList.toggle('hidden',!d.photoUrl);if(d.photoUrl)im.src=d.photoUrl;const link=shareUrl(d);drawQR($('#miniQr'),link,220);drawQR($('#qr'),link,520);$('#sharedBanner').classList.toggle('hidden',!isShared);$('#settingsBtn').classList.toggle('hidden',isShared);if(isShared&&record)saveHistory(d);updateFav();$('#card').classList.remove('flipped');show('#cardScreen')}
function formData(){return{name:$('#name').value.trim(),role:$('#role').value.trim(),company:$('#company').value.trim(),email:$('#email').value.trim(),phone:$('#phone').value.trim(),website:$('#website').value.trim(),photoUrl:$('#photoUrl').value.trim()}}
function fill(d={}){['name','role','company','email','phone','website','photoUrl'].forEach(k=>$('#'+k).value=d[k]||'')}
function renderHistory(){const list=$('#historyList'),h=read(HISTORY),f=read(FAV);list.innerHTML='';if(!h.length){list.innerHTML='<p style="color:#777;padding:8px">No scanned cards yet.</p>';return}h.sort((a,b)=>(f.includes(key(b))?1:0)-(f.includes(key(a))?1:0)||(b.time-a.time)).forEach(d=>{const row=document.createElement('article');row.className='historyItem';const open=document.createElement('button');open.innerHTML='<b></b><small></small>';open.querySelector('b').textContent=d.name||'Contact';open.querySelector('small').textContent=[d.role,d.company].filter(Boolean).join(' · ');open.onclick=()=>{$('#historyDialog').close();render(d,true,false)};const star=document.createElement('button');star.textContent=isFav(d)?'★':'☆';star.style.color='#ff7840';star.onclick=()=>favorite(d);row.append(open,star);list.append(row)})}
$('#startBtn').onclick=()=>{fill(read(STORE,{}));show('#editor')};$('#editorBack').onclick=()=>show(localStorage.getItem(STORE)?'#cardScreen':'#welcome');$('#cardForm').onsubmit=e=>{e.preventDefault();const d=formData();write(STORE,d);render(d)};$('#flipBtn').onclick=()=>$('#card').classList.add('flipped');$('#closeQr').onclick=()=>$('#card').classList.remove('flipped');$('#miniQr').onclick=()=>$('#card').classList.add('flipped');$('#favoriteBtn').onclick=()=>favorite(active);$('#shareBtn').onclick=async()=>{const link=shareUrl(active);try{if(navigator.share)await navigator.share({title:`${active.name}'s Smartcard`,text:'Connect with me through Smartcard by Phoen.',url:link});else{await navigator.clipboard.writeText(link);toast('Share link copied')}}catch{}};$('#vcfBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([vcard(active)],{type:'text/vcard'}));a.download=(active.name||'contact')+'.vcf';a.click();URL.revokeObjectURL(a.href)};
const settings=$('#settingsDialog'),history=$('#historyDialog');$('#settingsBtn').onclick=()=>settings.showModal();$('#historyBtn').onclick=()=>{renderHistory();history.showModal()};document.querySelectorAll('.closeDialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#editBtn').onclick=()=>{settings.close();fill(read(STORE,{}));show('#editor')};$('#resetBtn').onclick=()=>{localStorage.removeItem(STORE);settings.close();show('#welcome')};$('#clearHistory').onclick=()=>{localStorage.removeItem(HISTORY);renderHistory()};addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e});$('#installBtn').onclick=async()=>{if(promptEvent){promptEvent.prompt();await promptEvent.userChoice}else toast('Use your browser menu to install')};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));const sd=decode(new URLSearchParams(location.search).get('shared')||'');sd?render(sd,true):localStorage.getItem(STORE)?render(read(STORE,{})):show('#welcome');